GET http://localhost:5000/

### login
POST http://localhost:5000/login
content-type: application/json

{ "login":"letscode", "senha":"lets@123"}
 
### list all
GET http://localhost:5000/cards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoibGV0c2NvZGUiLCJpYXQiOjE2NzczNTQ1MjEsImV4cCI6MTY3NzM1ODEyMX0.JyF9WBvuESIjVV48-QjbaP7MojsQ5S-g8dn_jrDlhUc


### list one
GET http://localhost:5000/cards/6d00de34-5a48-4fe8-af5f-ef0ab7b8e4e7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoibGV0c2NvZGUiLCJpYXQiOjE2NzczNTQ1MjEsImV4cCI6MTY3NzM1ODEyMX0.JyF9WBvuESIjVV48-QjbaP7MojsQ5S-g8dn_jrDlhUc

### create
POST http://localhost:5000/cards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoibGV0c2NvZGUiLCJpYXQiOjE2NzczNTQ1MjEsImV4cCI6MTY3NzM1ODEyMX0.JyF9WBvuESIjVV48-QjbaP7MojsQ5S-g8dn_jrDlhUc
content-type: application/json

{
    "titulo": "Meu Titulo 1",
    "conteudo": "Conteudo do card no Kanban",
    "lista": "todo"
}

### update
PUT http://localhost:5000/cards/b3d265c5-773d-4b1d-a4a7-c5bd14c7cc11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoibGV0c2NvZGUiLCJpYXQiOjE2NzczNTQ1MjEsImV4cCI6MTY3NzM1ODEyMX0.JyF9WBvuESIjVV48-QjbaP7MojsQ5S-g8dn_jrDlhUc
content-type: application/json

{
    "id": "b3d265c5-773d-4b1d-a4a7-c5bd14c7cc11",
    "titulo": "Meu Titulo 101 DONE",
    "conteudo": "Term 1 Definition 1 [Abbreviations](https://github.com/markdown-it/markdown-it-abbr \n sdhuashduhsaudhushduas ",
    "lista": "done"
}

### delete
DELETE http://localhost:5000/cards/175dfe7a-9322-468b-bcbb-4ef7102c2a63
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoibGV0c2NvZGUiLCJpYXQiOjE2NzczNTQ1MjEsImV4cCI6MTY3NzM1ODEyMX0.JyF9WBvuESIjVV48-QjbaP7MojsQ5S-g8dn_jrDlhUc